### ISSUE TITLE
不兼容centos或ubuntu?

### ISSUE THREAD

**Issue by iceelee** [seasonstar/bibi-frontend#1]
请问你的环境是MacOS吗？
我试了64位的centos和ubuntu，gulp dev 和gulp deploy都报错：
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/root/code/bibi-frontend/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/root/code/bibi-frontend/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/code/bibi-frontend/node_modules/gulp-sass/index.js:163:21)

**Comment by wubuyun** [comment]
The Problem with gulp-util
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
